In [1]:
import numpy as np


def step_func(v, a=0):
    @np.vectorize
    def step_f(x):
        return 0 if x <= a else 1
    return step_f(v)

Введите веса
Введите величину порога


In [2]:
def McCulloch_Pitts_OR():
    print('Введите веса')
    w1 = float(input('Вес w1 = '))
    w2 = float(input('Вес w2 = '))
    print('Введите величину порога')
    theta = float(input('Порог = '))
    x1 = np.array([1, 1, 0, 0])
    x2 = np.array([1, 0, 1, 0])
    z = np.array([1, 1, 1, 0])

    while True:
        zin = x1*w1 + x2*w2

        y = step_func(zin, theta)

        print('Значение на выходе нейрона')
        print(y)

        if np.array_equal(y, z):
            break
        else:
            print(
                'Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
            w1 = float(input('Вес w1 = '))
            w2 = float(input('Вес w2 = '))
            theta = float(input('Порог = '))

    print('Нейрон МакКаллока-Питса для функции "ИЛИ" (англ. "OR")')
    print('Веса нейрона')
    print(w1)
    print(w2)
    print('Пороговое значение')
    print(theta)

In [3]:
McCulloch_Pitts_OR() # 1 1 0.5

Введите веса
Введите величину порога
Значение на выходе нейрона
[1 1 1 0]
Нейрон МакКаллока-Питса для функции "ИЛИ" (англ. "OR")
Веса нейрона
1.0
1.0
Пороговое значение
0.5


In [4]:
def McCulloch_Pitts_AND():
    print('Введите веса')
    w1 = float(input('Вес w1 = '))
    w2 = float(input('Вес w2 = '))
    print('Введите величину порога')
    theta = float(input('Порог = '))
    x1=np.array([1, 1, -1, -1])
    x2=np.array([1, -1, 1, -1])
    z=np.array([1, 0, 0, 0])

    while True:
        zin = x1*w1 + x2*w2

        y = step_func(zin, theta)

        print('Значение на выходе нейрона')
        print(y)

        if np.array_equal(y, z):
            break
        else:
            print(
                'Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
            w1 = float(input('Вес w1 = '))
            w2 = float(input('Вес w2 = '))
            theta = float(input('Порог = '))

    print('Нейрон МакКаллока-Питса для функции "И" (англ. "AND")')
    print('Веса нейрона')
    print(w1)
    print(w2)
    print('Пороговое значение')
    print(theta)

In [5]:
McCulloch_Pitts_AND()

Введите веса
Введите величину порога
Значение на выходе нейрона
[0 0 0 0]
Нейрон не обучен. Введите другие значения весовых коэффициентов и порога
Значение на выходе нейрона
[1 0 0 0]
Нейрон МакКаллока-Питса для функции "И" (англ. "AND")
Веса нейрона
2.0
2.0
Пороговое значение
1.0


In [32]:
def check_weights(x1=np.array([1, 1, 0, 0]),
                  x2=np.array([1, 0, 1, 0]),
                  y=np.array([0, 0, 0, 0])):

    def wrapper(w1, w2, theta):
        return np.array_equal(step_func(x1*w1 + x2*w2, theta), y)

    return wrapper

In [34]:
OR_f = check_weights(y=np.array([1, 1, 1, 0]))
print(OR_f(1, 1, 0.5))
AND_f = check_weights(x1=np.array([1, 1, -1, -1]),
                      x2=np.array([1, -1, 1, -1]),
                      y=np.array([1, 0, 0, 0]))
print(AND_f(2, 2, 1))

True
True


In [7]:
def McCulloch_Pitts_XOR():
    # Задание весов и значения порога
    print('Введите веса')
    w_11 = float(input('Вес w_11 ='))
    w_12 = float(input('Вес w_12 ='))
    w_21 = float(input('Вес w_21 ='))
    w_22 = float(input('Вес w_22 ='))
    w11 = float(input('Вес w11 ='))
    w12 = float(input('Вес w12 ='))

    print('Введите величину порога')
    theta = float(input('Порог ='))
    x1 = np.array([1, 1, 0, 0])
    x2 = np.array([1, 0, 1, 0])
    z = np.array([0, 1, 1, 0])
    while True:
        zin1 = x1*w_11+x2*w_21
        zin2 = x1*w_12+x2*w_22
        y1 = step_func(zin1, theta)
        y2 = step_func(zin2, theta)

        zin = y1*w11 + y2*w12

        y = step_func(zin, theta)
        print('Значение на выходе нейрона')
        print(y)
        if all(y == z):
            break
        else:
            print(
                'Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
            w_11 = float(input('Вес w_11 ='))
            w_12 = float(input('Вес w_12 ='))
            w_21 = float(input('Вес w_21 ='))
            w_22 = float(input('Вес w_22 ='))
            w11 = float(input('Вес w11 ='))
            w12 = float(input('Вес w12 ='))
            theta = float(input('Порог ='))
    print('Нейрон МакКаллока-Питса для функции "Исключащее-ИЛИ" (англ. "XOR")')
    print('Веса первого слоя')
    print([w_11,
           w_12,
           w_21,
           w_22])
    print('Веса второго слоя')
    print([w11,
           w12])
    print('Пороговое значение')
    print(theta)

In [9]:
McCulloch_Pitts_XOR()

Введите веса
Введите величину порога
Значение на выходе нейрона
[1 1 1 0]
Нейрон не обучен. Введите другие значения весовых коэффициентов и порога
Значение на выходе нейрона
[0 1 1 0]
Нейрон МакКаллока-Питса для функции "Исключащее-ИЛИ" (англ. "XOR")
Веса первого слоя
[2.0, -1.5, -1.5, 2.0]
Веса второго слоя
[2.0, 2.0]
Пороговое значение
1.0
